<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_atau_img-circle avatar</name>
   <tag></tag>
   <elementGuidId>e08b94ad-cc6b-445d-9ad9-b4dbc971d4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarInstance']/div/div/div/ul/li/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-circle.avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a1b971f9-6a6c-44e4-b916-ceb8f60a1381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle avatar</value>
      <webElementGuid>2c70a17f-9a03-4128-9153-c8025ad4de65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.qasir.id/production/newuser/original/cgxwRMbXTL7Cujang.PNG</value>
      <webElementGuid>ec83e8f0-15c0-4857-ad87-57d5f1aa6386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>8bbc0aa6-8d0d-4ff0-a495-12bf49e7c87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>813bcefb-df0b-476a-a23f-bd23017dd787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rahmanto ujang</value>
      <webElementGuid>ca9dfb09-8136-4d0e-9232-4e376cf618fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://kiddy-s-bookstore-695283.qasir.id/assets/images/no-image.png';</value>
      <webElementGuid>af3509de-b7b8-4003-abcf-6e1048bfeacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarInstance&quot;)/div[@class=&quot;navbar-inner container-fluid&quot;]/div[@class=&quot;topmenu-outer&quot;]/div[@class=&quot;top-menu-responsive&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;user-dropdown dropdown-toggle waves-effect waves-button waves-classic&quot;]/div[@class=&quot;user-image new-user-image&quot;]/img[@class=&quot;img-circle avatar&quot;]</value>
      <webElementGuid>af4a8201-7dfe-4216-8417-3195e9b8bc10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarInstance']/div/div/div/ul/li/a/div/img</value>
      <webElementGuid>9b3db2e3-8930-444d-9238-b1c400fcab08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rahmanto ujang']</value>
      <webElementGuid>b4e94159-c13d-4e69-a9a4-fd5029268b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>e3a72503-b1c2-4021-8891-231e8521de26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.qasir.id/production/newuser/original/cgxwRMbXTL7Cujang.PNG' and @alt = 'Rahmanto ujang']</value>
      <webElementGuid>675e18fa-da1a-46be-a336-04d3f2e5ec82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
