<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_atau_img-circle avatar border-free</name>
   <tag></tag>
   <elementGuidId>58ac0693-2e9c-485c-9b98-d41b2b8004a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarInstance']/div/div/div/ul/li/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-circle.avatar.border-free</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>30a8038f-2555-4535-8e29-e30ccb18a56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle avatar border-free</value>
      <webElementGuid>9a215a19-3c0f-4f4b-a854-6f227a315551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.qasir.id/production/newuser/original/cgxwRMbXTL7Cujang.PNG</value>
      <webElementGuid>de3c08a9-67e8-4a4e-90eb-f5cf6501333c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>9e5c6ecc-f200-454b-8851-db4bf5bd9754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>3bbbd187-8a18-4297-ae30-4bf31af7c99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rahmanto ujang</value>
      <webElementGuid>8b0ca72c-d36b-43ce-9904-6a25d4166941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://kiddy-s-bookstore-695283.qasir.id/assets/images/no-image.png';</value>
      <webElementGuid>7f39e9ca-3268-4bf3-8cca-fc3cf0963e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarInstance&quot;)/div[@class=&quot;navbar-inner container-fluid&quot;]/div[@class=&quot;topmenu-outer&quot;]/div[@class=&quot;top-menu-responsive&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;user-dropdown dropdown-toggle waves-effect waves-button waves-classic&quot;]/div[@class=&quot;user-image new-user-image&quot;]/img[@class=&quot;img-circle avatar border-free&quot;]</value>
      <webElementGuid>a59a2574-ec30-44a8-a4ca-cbb4d167f56b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarInstance']/div/div/div/ul/li/a/div/img</value>
      <webElementGuid>fb1a49ea-53b5-42fa-b926-049753129378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rahmanto ujang']</value>
      <webElementGuid>d0fccd83-0700-49e6-b053-1c1896402f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>117a5460-8fa0-4f4e-bbf0-a87dd6151105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.qasir.id/production/newuser/original/cgxwRMbXTL7Cujang.PNG' and @alt = 'Rahmanto ujang']</value>
      <webElementGuid>ccab5fea-213a-4d59-9825-83a3f9e8f571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
