<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Pusat</name>
   <tag></tag>
   <elementGuidId>21ce3c73-5d2d-46f2-9f81-c459a933df41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-select-outlet']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.outlet-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0ca6ea0e-120a-4c23-b29d-54cdd2511685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outlet-name</value>
      <webElementGuid>a57ab551-248a-450c-8216-234e7dca4449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pusat</value>
      <webElementGuid>4574a860-a12b-4dd7-8063-f4d69dedd9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-select-outlet&quot;)/div[@class=&quot;item-select-outlet&quot;]/div[@class=&quot;item-wrap-select-outlet&quot;]/div[@class=&quot;outlet-desc&quot;]/h4[@class=&quot;outlet-name&quot;]</value>
      <webElementGuid>bdcb4fe7-52fc-4c7a-85e0-386258220ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-select-outlet']/div/div/div/h4</value>
      <webElementGuid>c10326e8-4d8e-4fab-8d18-4c65c88ce04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Outlet'])[1]/following::h4[1]</value>
      <webElementGuid>e4076729-c96c-425f-b920-4de358ca0f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Toko'])[1]/following::h4[1]</value>
      <webElementGuid>0c0fc83e-225b-4a32-b0e6-e5370d0561f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utan Kayu Selatan, Matraman, Kota Jakarta Timur'])[1]/preceding::h4[1]</value>
      <webElementGuid>4debd761-5068-41ef-a1dc-cdb55562a03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kizu'])[1]/preceding::h4[1]</value>
      <webElementGuid>bd3055ea-db86-4fb7-a363-bb5b89b445f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pusat']/parent::*</value>
      <webElementGuid>d8ca9460-1085-455f-9da4-91cea3e61441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/h4</value>
      <webElementGuid>b10c84ba-b2be-4290-b901-8c5e7c4f5e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Pusat' or . = 'Pusat')]</value>
      <webElementGuid>c207d6c6-206e-4c54-aac0-a791af5a88be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
