<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. PIN_submit-btn-signin</name>
   <tag></tag>
   <elementGuidId>4e960226-b8b0-47cb-8e2f-31d821fe3992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit-btn-signin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-btn-signin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>894a48b5-39ff-41e7-84f2-96cc931031f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>75236611-a22f-4e39-9da5-b06af2c801e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>593283df-45c2-447d-96f7-18f5fed06f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wait</name>
      <type>Main</type>
      <value>Mohon tunggu...</value>
      <webElementGuid>b3788dd8-1b5c-420b-8b20-19b9e985ca5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-btn-signin</value>
      <webElementGuid>4addb983-75a3-4663-b172-ca330fe5372d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>login-button-signin</value>
      <webElementGuid>10956ffd-c3b3-44e0-8d30-2bf9c4111420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button w-button</value>
      <webElementGuid>f87a872a-6d20-4fef-a318-395a3c198c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-btn-signin&quot;)</value>
      <webElementGuid>203b436d-3207-423b-b0b5-cbafe8de43b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit-btn-signin']</value>
      <webElementGuid>488d9947-cfde-4b41-8c09-7fc72954d524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-phone']/div/input</value>
      <webElementGuid>fe412c5f-5f49-4e34-b8a8-f5f52f59896a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>47246ebc-98f3-4130-91dd-e29833886d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'submit-btn-signin']</value>
      <webElementGuid>dbf687b2-03e9-4d5a-9203-71acdc8ec279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
