<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phonenumber</name>
   <tag></tag>
   <elementGuidId>928b7b43-7997-424c-98d1-ac5950d73423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-in-phonenumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sign-in-phonenumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46777ad3-1806-45a4-8370-5373745f11f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>082d6711-cc03-4559-8b2f-7458bf02f6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-control-input field-control-input-phone w-input</value>
      <webElementGuid>4767f281-e112-4162-abe5-29bf25fa222f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>b6561ff7-9f16-457d-8af3-4c6f58f53c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>e8b386dc-dda7-43a1-a8b9-993d28533a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>phonenumber</value>
      <webElementGuid>fbe7bc04-5cc4-4b83-bf67-4cc339f17dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>login-textfield-phonenumber</value>
      <webElementGuid>edb6fddc-4145-4ec8-b7a7-0c61e35ffd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-in-phonenumber</value>
      <webElementGuid>c2248936-a7b6-4b6f-8f8e-1bb885f92acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18877378-3fa0-47c7-a785-c169269f59db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in-phonenumber&quot;)</value>
      <webElementGuid>24a7dd5d-72eb-4831-be13-b087684c13a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-in-phonenumber']</value>
      <webElementGuid>7592fbb1-cff9-4d0b-96e1-5a22699ba2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-tabs-0-data-w-pane-0']/div/div[2]/input</value>
      <webElementGuid>9b13ab4d-344b-4275-85ad-04b4f233bb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>90bbb846-a77b-4284-9237-7d6ecaade166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'phonenumber' and @id = 'sign-in-phonenumber']</value>
      <webElementGuid>e79f390d-88aa-45ec-87df-d2e20ebccd75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
